---
- hosts: minikube_nodes
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - conntrack
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      check_mode: no

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
        state: present
        update_cache: yes
      check_mode: no

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Ensure docker group exists
      group:
        name: docker
        state: present
      check_mode: no

    - name: Add adminuser to docker group
      user:
        name: adminuser
        groups: docker
        append: yes
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Install kubectl
      get_url:
        url: "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Start Minikube
      become: yes
      become_user: adminuser
      shell: |
        minikube start --driver=docker --listen-address=0.0.0.0
      register: minikube_output
      changed_when: "'Done!' in minikube_output.stdout or 'Starting' in minikube_output.stdout"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Wait for Minikube to be ready
      become: yes
      become_user: adminuser
      shell: kubectl wait --for=condition=Ready nodes --all --timeout=60s
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Verify Minikube Access (Proxy Test)
      run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -L 8001:localhost:8001 adminuser@${{ env.VM_IP }} "kubectl proxy" &
          sleep 5
          curl -s http://localhost:8001/version || exit 1
          echo "Minikube API is accessible via SSH Tunnel!"