name: Task 3 Build and Deploy

on:
  push:
    branches:
      - develop
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repo (for manifests)
        uses: actions/checkout@v4

      - name: Checkout external app repo
        uses: actions/checkout@v4
        with:
          repository: YulianSalo/devops-exam-pt2
          ref: main
          path: app-source

      - name: Set Environment Variables
        run: |
          if [[ ${{ github.ref }} == refs/tags/* ]]; then
            echo "ENV_NAME=release" >> $GITHUB_ENV
            echo "APP_PORT=8003" >> $GITHUB_ENV
            echo "DOCKER_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "ENV_NAME=dev" >> $GITHUB_ENV
            echo "APP_PORT=8002" >> $GITHUB_ENV
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/tesliuk-app:${{ env.DOCKER_TAG }}
          docker build -t $IMAGE_NAME ./app-source
          docker push $IMAGE_NAME

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get VM IP
        run: |
          IP=$(az network public-ip show --resource-group tesliuk-rg --name tesliuk-pip --query ipAddress -o tsv)
          echo "VM_IP=$IP" >> $GITHUB_ENV

      - name: Copy manifest to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.VM_IP }}
          username: adminuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "task3/k8s.yaml"
          target: "~/"
          strip_components: 1

      - name: Deploy to Minikube
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VM_IP }}
          username: adminuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ENV_NAME,APP_PORT,DOCKER_TAG,DOCKER_HUB_USERNAME
          script: |
            export DOCKER_IMAGE="${DOCKER_HUB_USERNAME}/tesliuk-app:${DOCKER_TAG}"
            envsubst < ~/k8s.yaml > ~/k8s_${ENV_NAME}.yaml
            sg docker -c "kubectl apply -f ~/k8s_${ENV_NAME}.yaml"
        env:
          ENV_NAME: ${{ env.ENV_NAME }}
          APP_PORT: ${{ env.APP_PORT }}
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}